In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer

#データの読み込み
cancer = load_breast_cancer()

#学習用データとテスト用データに分割
X_train, X_test, Y_train, Y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=10)

# ロジスティック回帰
clf = LogisticRegression(max_iter=10000, random_state=10) 
clf.fit(X_train, Y_train)

#結果
print("学習用データの精度：{:.3f}".format(clf.score(X_train, Y_train)))
print("テスト用データの精度：{:.3f}".format(clf.score(X_test, Y_test)))

学習用データの精度：0.967
テスト用データの精度：0.944


In [18]:
print(cancer.feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [19]:
print(clf.coef_)

[[ 1.18735277  0.10956117 -0.34424801  0.03058382 -0.13697868 -0.24420076
  -0.47417791 -0.25823461 -0.16411383 -0.04076821 -0.10834608  0.98480834
   0.51366471 -0.15573578 -0.01774663  0.00548093 -0.05640094 -0.032573
  -0.03970233 -0.00146958  0.29506321 -0.38702693 -0.12196145 -0.01622899
  -0.26743725 -0.60707092 -1.12130676 -0.48197736 -0.52267118 -0.09852384]]


In [20]:
print(clf.coef_.reshape(30,-1))

[[ 1.18735277]
 [ 0.10956117]
 [-0.34424801]
 [ 0.03058382]
 [-0.13697868]
 [-0.24420076]
 [-0.47417791]
 [-0.25823461]
 [-0.16411383]
 [-0.04076821]
 [-0.10834608]
 [ 0.98480834]
 [ 0.51366471]
 [-0.15573578]
 [-0.01774663]
 [ 0.00548093]
 [-0.05640094]
 [-0.032573  ]
 [-0.03970233]
 [-0.00146958]
 [ 0.29506321]
 [-0.38702693]
 [-0.12196145]
 [-0.01622899]
 [-0.26743725]
 [-0.60707092]
 [-1.12130676]
 [-0.48197736]
 [-0.52267118]
 [-0.09852384]]


In [3]:
import pandas as pd

#回帰係数を分かりやすいように表にする

coef = pd.DataFrame(clf.coef_.reshape((30, -1)), cancer.feature_names, columns=["回帰係数"])
interce = pd.DataFrame([clf.intercept_], index=["定数項"], columns=["回帰係数"])
df_coef = pd.concat([coef, interce])
df_coef

回帰係数
mean radius               1.187353
mean texture              0.109561
mean perimeter           -0.344248
mean area                 0.030584
mean smoothness          -0.136979
mean compactness         -0.244201
mean concavity           -0.474178
mean concave points      -0.258235
mean symmetry            -0.164114
mean fractal dimension   -0.040768
radius error             -0.108346
texture error             0.984808
perimeter error           0.513665
area error               -0.155736
smoothness error         -0.017747
compactness error         0.005481
concavity error          -0.056401
concave points error     -0.032573
symmetry error           -0.039702
fractal dimension error  -0.001470
worst radius              0.295063
worst texture            -0.387027
worst perimeter          -0.121961
worst area               -0.016229
worst smoothness         -0.267437
worst compactness        -0.607071
worst concavity          -1.121307
worst concave points     -0.481977
worst symmetry           -0.522671
worst fractal dimension  -0.098524
定数項                      28.821705

In [11]:
print(cancer["feature_names"])

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [12]:
print(cancer["target_names"])

['malignant' 'benign']


In [17]:
print(X_train)

[[2.031e+01 2.706e+01 1.329e+02 ... 1.697e-01 3.151e-01 7.999e-02]
 [1.176e+01 1.814e+01 7.500e+01 ... 7.160e-02 1.978e-01 6.915e-02]
 [1.760e+01 2.333e+01 1.190e+02 ... 1.996e-01 2.301e-01 1.224e-01]
 ...
 [1.125e+01 1.478e+01 7.138e+01 ... 1.667e-02 2.815e-01 7.418e-02]
 [1.193e+01 1.091e+01 7.614e+01 ... 6.876e-02 2.460e-01 7.262e-02]
 [1.071e+01 2.039e+01 6.950e+01 ... 8.600e-02 2.605e-01 8.701e-02]]


In [23]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

#Test the model
predictions = clf.predict(X_test)
print(predictions)# printing predictions

print()# Printing new line

#Check precision, recall, f1-score
print( classification_report(Y_test, predictions) )

print( accuracy_score(Y_test, predictions))

[1 1 1 0 0 1 1 1 0 0 1 0 1 0 1 1 1 1 0 0 1 1 0 0 1 1 1 0 1 1 1 0 1 0 0 1 1
 0 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1
 1 0 0 1 0 1 0 0 1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 0 1 0
 1 0 1 1 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 1 1 1 1 1 0 1 0]

              precision    recall  f1-score   support

           0       0.94      0.91      0.92        53
           1       0.95      0.97      0.96        90

    accuracy                           0.94       143
   macro avg       0.94      0.94      0.94       143
weighted avg       0.94      0.94      0.94       143

0.9440559440559441
