In [38]:
import numpy as np
import pandas as pd
from sklearn import datasets

iris = datasets.load_iris()

In [39]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

In [72]:
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = iris.data[:,:2]
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [47]:
clf = LogisticRegression(random_state=1)
clf.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [48]:
y_pred = clf.predict(X_test)

In [49]:
accuracy_score(y_test, y_pred)

0.7894736842105263

In [118]:
Y_pred = clf.predict(X_test)
print(Y_pred)

[0 1 2 0 2 2 2 0 0 2 1 0 2 2 1 0 1 1 0 0 1 0 2 0 2 1 0 0 1 1 2 2 1 2 1 0 1
 0]


In [125]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

print('confusion matrix = \n', confusion_matrix(y_true=y_test, y_pred=y_pred))
print('accuracy = ', accuracy_score(y_true=y_test, y_pred=y_pred))

confusion matrix = 
 [[13  0  0]
 [ 1 10  5]
 [ 0  2  7]]
accuracy =  0.7894736842105263


In [69]:
clf.coef_

array([[-2.47910598,  1.99879973],
       [ 0.63995504, -1.51084671],
       [ 1.83915094, -0.48795302]])

In [71]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [79]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [109]:
print(clf.coef_.reshape(6,-1))

[[-2.47910598]
 [ 1.99879973]
 [ 0.63995504]
 [-1.51084671]
 [ 1.83915094]
 [-0.48795302]]


In [116]:
import pandas as pd
coef = pd.DataFrame(clf.coef_.reshape(6,-1),columns=["回帰係数"])
interce = pd.DataFrame([clf.intercept_], index=["定数項"])
df_coef = pd.concat([coef, interce])
df_coe

回帰係数         0        1         2
0   -2.479106       NaN      NaN       NaN
1    1.998800       NaN      NaN       NaN
2    0.639955       NaN      NaN       NaN
3   -1.510847       NaN      NaN       NaN
4    1.839151       NaN      NaN       NaN
5   -0.487953       NaN      NaN       NaN
定数項       NaN  7.635044  1.28668 -8.921724